### PR TITLE
Added ability to specify default dispatcher transport CA pool

### PR DESCRIPTION
**Pull request by jbornemann**
Normally, I imagine this can be done by altering a given client's base client; however some communication happens before a client is even created; such as in the principal key provider - and in rare circumstances, the default transport won't do. 

For particular environments, we need to set root CAs for all communication to those cloud API endpoints.

### CODE REVIEW

**Comment by jasonyin** [comment]
> > Thanks @jbornemann for submitting the PR. I am just wondering would this works for you?
> > ```go
> > client, err := [Create your client]
> > client.HTTPClient = &http.Client{
> > 	Transport: &http.Transport{
> > 		TLSClientConfig: &tls.Config{
> > 				RootCAs:[cert],
> > 			},
> > 	}
> > }
> > ```
> 
> Unfortunately not in the particular case I am addressing. The principal key provider, as an example, is using the default dispatcher before a client is created.

Got it, I am trying to understand more about your use case. Were you referring to the 'federationClient' for instance principle?

Also, for non-instance principle scenario, are you currently using the approach I mentioned before?

**Comment by jbornemann** [comment]
Right. When using instance principal, the federation client uses the auth client created here https://github.com/oracle/oci-go-sdk/blob/master/common/auth/federation_client.go#L45 , then when instantiating the configuration, it eventually makes a call here https://github.com/oracle/oci-go-sdk/blob/master/common/auth/federation_client.go#L146 . This fails for me because my OCI environment's CA chain is not loaded into the auth client created above. 

In the non-principal scenario using raw configuration, it isn't an issue. I can eventually use the client successfully, by using similar code to what you have above. 

It feels a bit off to have to use an environment variable for this, but I figured since it is a less-than-likely scenario normally, it may be appropriate.

**Comment by jasonyin** [comment]
hi @jbornemann, I am thinking to do it in a little bit different way. Something like when you create an InstancePrinciple provider, we will add a new method which takes a function(callback) to customize the client instead of using the env var. This way, user can add their own cert, change the proxy, etc...
What do you think?

**Comment by jbornemann** [comment]
Yeah! I'm for that @jasonyin. I'll make the changes.

**Comment by eginez** [comment]
Closing this pull request as this change will be available in the next release, thanks again for the PR @jbornemann

**Pull request closed without merging**
