### PR TITLE
Improve user_data metadata example

### PR DESCRIPTION
**Pull request by eduherminio**
* Replace`<your_public_SSH_key>` with `<your_base64_encoded_user_data>` in `metadata.user_data` example.

### CODE REVIEW

**Review by pelliu — COMMENTED** [review]
@eduherminio, firstly, thanks for providing the pull request to OCI Go SDK, I understand you want to update the comment part of our Compute Service, however, this code is auto-generated from the service spec, if need to update, have to update from the service end, otherwise next week when we release new version Go SDK, it would be overridden, if you don't mind, would you like to go to our OCI console to file a service request to Compute Service?

**Comment by eduherminio** [comment]
I tried to follow [this](https://docs.oracle.com/en-us/iaas/goldengate/doc/submit-support-request.html?Highlight=service%20request), tried to find my `Support Identifier` and gave up after 10 mins.

**Comment by pelliu** [comment]
I will create a ticket to compute service internally and update to you, @eduherminio .

**Comment by eduherminio** [comment]
Cheers @pelliu, because I ended up stuck here

image

**Comment by pelliu** [comment]
Awesome! thanks @eduherminio!

**Pull request closed without merging**
